db:
    host: "localhost"
    port: 5433
    user: "postgres"
    password: "mypass"
    name: "orderdb"
nats:
    host: "localhost"
    port: 4223
    clusterID: "wb-cluster"
    clientID: "clientOrder"