kafka:
  broker: "localhost:9092" 
  group_id: "my-group"
  topic: "my-topic"   

postgres:
  host: "db"
  port: 5432    
  user: "postgres"
  password: "mypass"
  dbname: "orderdb"

memcached:
  host: "memcached"
  port: "11211"
