kafka:
  broker: "localhost"  # Имя контейнера Kafka в Docker-сети
  port: "9092"     # Внутри Docker сети Kafka слушает на 9092 порту
  topic: "orders"

postgres:
  host: "localhost"       # Имя контейнера Postgres в Docker-сети
  port: "5432"
  user: "postgres"
  password: "mypass"
  dbname: "orderdb"
