version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
      - kafka
      - memcached
    environment:
      - DATABASE_URL=postgres://postgres:mypass@db:5432/orderdb
      - KAFKA_BROKER=kafka:9092
      - MEMCACHED_HOST=memcached:11211
    restart: always

  db:
    container_name: db
    tty: true
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2182:2181"
    restart: always

  kafka:
    container_name: kafka
    tty: true
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Changed localhost to kafka
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
    depends_on:
      - zookeeper
    

  memcached:
    container_name: memcached
    image: memcached:alpine
    ports:
      - "11211:11211"
    restart: always
      