version: '3'

services:
  db:
    container_name: db
    ports: 
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydatabase
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data