version: '3.8'

services:
  db:
    container_name: db
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/postgresql/data

  nats:
    container_name: nats
    image: nats-streaming:alpine
    ports:
      - 4223:4222 # Основной порт для клиентских подключений
      - 8222:8222 # Порт для мониторинга и управления

  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"