// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/postgres/postgres.go

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	reflect "reflect"
	models "wb-kafka-service/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockPostgresDB is a mock of PostgresDB interface.
type MockPostgresDB struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresDBMockRecorder
}

// MockPostgresDBMockRecorder is the mock recorder for MockPostgresDB.
type MockPostgresDBMockRecorder struct {
	mock *MockPostgresDB
}

// NewMockPostgresDB creates a new mock instance.
func NewMockPostgresDB(ctrl *gomock.Controller) *MockPostgresDB {
	mock := &MockPostgresDB{ctrl: ctrl}
	mock.recorder = &MockPostgresDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresDB) EXPECT() *MockPostgresDBMockRecorder {
	return m.recorder
}

// GetOrderFromDB mocks base method.
func (m *MockPostgresDB) GetOrderFromDB(ctx context.Context, orderID int) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderFromDB", ctx, orderID)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderFromDB indicates an expected call of GetOrderFromDB.
func (mr *MockPostgresDBMockRecorder) GetOrderFromDB(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderFromDB", reflect.TypeOf((*MockPostgresDB)(nil).GetOrderFromDB), ctx, orderID)
}

// InsertOrderToDB mocks base method.
func (m *MockPostgresDB) InsertOrderToDB(ctx context.Context, order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrderToDB", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrderToDB indicates an expected call of InsertOrderToDB.
func (mr *MockPostgresDBMockRecorder) InsertOrderToDB(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrderToDB", reflect.TypeOf((*MockPostgresDB)(nil).InsertOrderToDB), ctx, order)
}
